/* include/log4cxx/config_auto.h.  Generated by configure.  */
/* include/log4cxx/config_auto.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <alloca.h> header file. */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the <boost/regex.hpp> header file. */
#define HAVE_BOOST_REGEX_HPP 1

/* SMTP support through Microsoft CDO. */
/* #undef HAVE_CDO_SMTP */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the `ftime' function. */
#define HAVE_FTIME 1

/* Define to 1 if you have the `gethostbyname' function. */
#define HAVE_GETHOSTBYNAME 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <io.h> header file. */
/* #undef HAVE_IO_H */

/* ODBC support through iODBC. */
/* #undef HAVE_I_ODBC */

/* Define to 1 if you have the `boost_regex' library (-lboost_regex). */
#define HAVE_LIBBOOST_REGEX 1

/* Define to 1 if you have the `nsl' library (-lnsl). */
/* #undef HAVE_LIBNSL */

/* SMTP support through libsmtp library. */
/* #undef HAVE_LIBSMTP */

/* Define to 1 if you have the `smtp_mime' library (-lsmtp_mime). */
/* #undef HAVE_LIBSMTP_MIME */

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* XML support through libxml2. */
#define HAVE_LIBXML2 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* ODBC support through Microsoft ODBC. */
/* #undef HAVE_MS_ODBC */

/* thread support through Microsoft threads. */
/* #undef HAVE_MS_THREAD */

/* ODBC support through Microsoft XML. */
/* #undef HAVE_MS_XML */

/* no explicit exports */
#define LOG4CXX_EXPORT

/* ODBC support */
/* #undef HAVE_ODBC */

/* thread support through pthread library. */
#define HAVE_PTHREAD 1

/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have the `setsockopt' function. */
#define HAVE_SETSOCKOPT 1

/* SMTP support */
/* #undef HAVE_SMTP */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `syslog' function. */
#define HAVE_SYSLOG 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* thread support */
#define HAVE_THREAD 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* ODBC support through unixODBC. */
/* #undef HAVE_UNIX_ODBC */

/* XML support */
#define HAVE_XML 1

/* Defined to 1 if macro _T has to be undefined */
/* #undef MUST_UNDEF_T */

/* Name of package */
#define PACKAGE "log4cxx"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* UTF-16 Unicode support. */
/* #undef UNICODE */

/* Version number of package */
#define VERSION "0.9.7"
